[package]
name = "binlog_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql_binlog = { git = "https://github.com/EasyPost/rust-mysql-binlog" }
serde_json = "1.0"